services:
  web:
    build: .
    container_name: projectname_web
    command: bash -lc "rm -f tmp/pids/server.pid && bin/rails db:prepare && bin/rails s -b 0.0.0.0"
    tty: true
    stdin_open: true
    user: "${UID}:${GID}"    
    environment:
      RAILS_ENV: development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      RAILS_MASTER_KEY: "${RAILS_MASTER_KEY}"
    volumes:
      - .:/rails
      - builds:/rails/app/assets/builds
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - projectname_network
      
  db:
    image: postgres:17
    container_name: projectname_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - projectname_network


volumes:
  postgres_data:
  builds:

networks:
  projectname_network:
    driver: bridge